# Dein Gruppenname, z.B dbp001
gruppenname=dbp007
# Das dazugehörige Passwort
passwort=aegee3oo
# Name des Rechners im DB-Pool, eine Liste von Rechnernamen ist außerdem auf der Vorlesungsseite verlinkt.
rechnername=atlas
# Die Datenbank, z.B. funder
database=funder
